export const FIRESTORE_DOCUMENT_COLLECTION = 'documents';
export const FIRESTORE_USER_COLLECTION = 'users';
export const IGNORED_PERSONALID = '1111111111111';
export const OFFLINE_DOCUMENTS_COUNT = 6700;
